# Generated by Django 2.2 on 2021-06-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_note', '0012_auto_20210601_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
    ]
