# Generated by Django 2.2 on 2021-06-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_note', '0013_auto_20210602_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dt_created',
            field=models.DateField(auto_now_add=True, verbose_name='Date Created'),
        ),
    ]
